function dist = KLDiv(P,Q)
% P = M_A1_slct; Q = M_A2_slct;

mu_p = mean(P);mu_q = mean(Q);
sigma_p = cov(P);sigma_q = cov(Q);


dist = 1*(...
    trace((sigma_p)\sigma_q)...
    +(mu_p-mu_q)/(sigma_p)*(mu_p-mu_q)'...
    -size(P,2)...
    +log(det(sigma_p)/det(sigma_q))...
    );

% dist = 1*(...
%     trace((sigma_p)\sigma_q)...
%     +(mu_p-mu_q)/(sigma_p)*(mu_p-mu_q)'...
%     -size(P,2));

% dist = 1*(...
%     trace(inv(sigma_p)*sigma_q)...
%     +(mu_p-mu_q)*inv(sigma_p)*(mu_p-mu_q)'...
%     -size(P,2)...
%     +log(det(sigma_p)/det(sigma_q))...
%     );

end
